import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {NavLink} from 'react-router-dom';
import {api} from './api';
import {Empty,ErrorState,Skeleton} from './components';

const templates:Record<string,Record<string,any>>={
  laboratories:{name:'',code:'',country:'IL',active:true},
  analytes:{code:'',display_name_he:'',display_name_en:'',category:'CBC',description_he:'',typical_unit:'',comparison_direction:'RANGE',active:true},
  'reference-ranges':{analyte_id:1,laboratory_id:null,sex:null,age_min:null,age_max:null,unit:'',min_value:0,max_value:1,valid_from:null,valid_to:null,source_reference:'',active:true},
  'critical-thresholds':{analyte_id:1,laboratory_id:1,unit:'',low_value:null,high_value:null,source_reference:'',active:false},
  recommendations:{rule_code:'',title_he:'',content_he:'',severity:'INFO',evidence_source:'',active:true},
};
const names:Record<string,string>={laboratories:'מעבדות',analytes:'מדדים','reference-ranges':'טווחי ייחוס','critical-thresholds':'ספים קריטיים',recommendations:'כללי המלצה'};
const labels:Record<string,string>={name:'שם',code:'קוד',country:'מדינה',active:'פעיל',display_name_he:'שם בעברית',display_name_en:'שם באנגלית',category:'קטגוריה',description_he:'הסבר בעברית',typical_unit:'יחידה',comparison_direction:'בסיס השוואה',analyte_id:'מזהה מדד',laboratory_id:'מזהה מעבדה',sex:'מין ביולוגי',age_min:'גיל מינימלי',age_max:'גיל מקסימלי',unit:'יחידה',min_value:'גבול תחתון',max_value:'גבול עליון',valid_from:'בתוקף מתאריך',valid_to:'בתוקף עד',source_reference:'מקור מאומת',low_value:'סף נמוך',high_value:'סף גבוה',rule_code:'קוד כלל',title_he:'כותרת',content_he:'תוכן',severity:'חומרה',evidence_source:'מקור'};
export function Management(){
  const [resource,setResource]=useState('laboratories');const [draft,setDraft]=useState<Record<string,any>|null>(null);const [error,setError]=useState('');const qc=useQueryClient();
  const q=useQuery({queryKey:['config',resource],queryFn:()=>api.config(resource)});
  const audit=useQuery({queryKey:['audit'],queryFn:api.audit});
  const save=async()=>{if(!draft)return;try{const {id,...body}=draft;await api.saveConfig(resource,body,id);setDraft(null);setError('');await qc.invalidateQueries({queryKey:['config']});await qc.invalidateQueries({queryKey:['audit']});}catch(e){setError((e as Error).message)}};
  return <div><h1 className="text-3xl font-black">ניהול וביקורת</h1><div className="my-5 flex flex-wrap gap-2">{Object.entries(names).map(([key,label])=><button className={key===resource?'btn-primary':'btn-soft'} key={key} onClick={()=>{setResource(key);setDraft(null)}}>{label}</button>)}</div><button className="btn-primary mb-4" onClick={()=>setDraft({...templates[resource]})}>הוספת רשומה</button>{error&&<ErrorState message={error}/>} {draft&&<form className="card mb-5 grid gap-4 p-5 md:grid-cols-3" onSubmit={e=>{e.preventDefault();save()}}>{Object.entries(draft).filter(([key])=>key!=='id').map(([key,value])=><label key={key}><span className="label">{labels[key]||key}</span>{typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>:<input className="field" value={value??''} onChange={e=>{const raw=e.target.value;const numeric=['analyte_id','laboratory_id','age_min','age_max','min_value','max_value','low_value','high_value'].includes(key);setDraft({...draft,[key]:raw===''?null:numeric?Number(raw):raw})}}/>}</label>)}<div className="flex gap-2"><button className="btn-primary">שמירה</button><button type="button" className="btn-soft" onClick={()=>setDraft(null)}>ביטול</button></div></form>}{q.isLoading?<Skeleton/>:q.error?<ErrorState message={(q.error as Error).message}/>:<div className="card overflow-auto"><table className="w-full text-right"><thead><tr><th className="p-3">מזהה</th><th>רשומה</th><th>מצב</th><th>פעולה</th></tr></thead><tbody>{q.data?.map(row=><tr className="border-t" key={row.id}><td className="p-3">{row.id}</td><td>{row.name||row.display_name_he||row.title_he||`${row.analyte_id} · ${row.unit} · ${row.source_reference}`}</td><td>{row.active?'פעיל':'לא פעיל'}</td><td><button className="btn-soft" onClick={()=>setDraft({...row})}>עריכה</button></td></tr>)}</tbody></table></div>}<h2 className="my-5 text-xl font-bold">יומן ביקורת</h2><div className="card overflow-auto"><table className="w-full text-right"><tbody>{audit.data?.map(row=><tr className="border-b" key={row.id}><td className="p-3">{new Date(row.timestamp).toLocaleString('he-IL')}</td><td>{row.action}</td><td>{row.entity_type}</td><td>{row.user_id}</td></tr>)}</tbody></table></div></div>;
}
export function AlertCenter(){const qc=useQueryClient();const [error,setError]=useState('');const q=useQuery({queryKey:['alerts'],queryFn:api.alerts});return <div><h1 className="mb-6 text-3xl font-black">מרכז התראות</h1>{error&&<ErrorState message={error}/>} {q.isLoading?<Skeleton/>:q.error?<ErrorState message={(q.error as Error).message}/>:!q.data?.length?<Empty title="אין התראות" body="התראות נוצרות מניתוח נתוני הבדיקות."/>:<div className="space-y-3">{q.data.map(a=><div className="card p-5" key={a.id}><h2 className="font-bold">{a.title_he}</h2><p className="my-2">{a.state==='NEW'?'חדש':a.state==='READ'?'נקרא':'טופל'}</p><div className="flex gap-2"><NavLink className="btn-soft" to={`/tests/${a.test_id}`}>פתיחת בדיקה</NavLink>{['READ','RESOLVED'].map(state=><button className="btn-soft" disabled={a.state===state} key={state} onClick={async()=>{try{await api.setAlert(a.id,state);await qc.invalidateQueries({queryKey:['alerts']})}catch(e){setError((e as Error).message)}}}>{state==='READ'?'סימון כנקרא':'סימון כטופל'}</button>)}</div></div>)}</div>}</div>}
